'use client';

import { useRecoilValue, useSetRecoilState } from 'recoil';
import { useState, useEffect } from 'react';
import { ProfileAtom } from '@/state/profile.atom';
import { useProfileActions } from '@/actions/profile';
import { IProfile } from '@/interface/profile.interface';
import { useWallet } from '@txnlab/use-wallet';
import { useCountriesStates } from '@/hooks/useCountriesStates';
import { CameraIcon, Loader2 } from 'lucide-react';
import CountrySelect from '../form-field/country-select';
import StateSelect from '../form-field/state-select';
import { toast } from 'react-hot-toast';



interface EditProfileProps {
  onClose: () => void;
}



const EditProfile = ({ onClose }: EditProfileProps) => {
    const { updateProfile, getProfile, uploadImage } = useProfileActions();
    const {  states, fetchStates, loadingStates } =
        useCountriesStates();
    
    const setProfile = useSetRecoilState(ProfileAtom);
    const [uploading, setUploading] = useState(false);

  const [loading, setLoading] = useState(false);
  const profile = useRecoilValue(ProfileAtom);
  const { activeAddress } = useWallet();
  const [formData, setFormData] = useState<IProfile>({
    id: '', // usually generated by backend
    firstName: '',
    lastName: '',
    email: '',
    image: '',
    country: '',
    stateOfResidence: '',
    githubLink: '',
    walletAddress: '',
    awardedAlgos: 0,
  });

  useEffect(() => {
    if (!profile?.firstName) {
      getProfile(); // fetch if not loaded
    }
  }, []);

  useEffect(() => {
    if (profile?.firstName) {
      setFormData(profile);
    }
  }, [profile]);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (loading) return;
    setLoading(true);
    const response = await updateProfile(formData);
    if (response) {
      await getProfile();
      setLoading(false);
      toast.success('Profile updated successfully!',);
        onClose();
    }
    };
    
    const handleImageUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
      const file = e.target.files?.[0];
      if (!file) return;

      const previewUrl = URL.createObjectURL(file);
      setFormData((prev) => ({
        ...prev,
        image: previewUrl, // temporary preview
      }));
    
      const reader = new FileReader();

      reader.onloadend = async () => {
        const fullBase64 = reader.result?.toString();
        if (!fullBase64) return;

        const base64 = fullBase64.split(',')[1];
        const toastId = toast.loading('Uploading image...');

        try {
          const response = await uploadImage(base64);

          if (response?.imageUrl) {
            // ✅ Update local formData
            setFormData((prev) => ({
              ...prev,
              image: response.imageUrl,
            }));

            // ✅ Update Recoil profile state immediately
            setProfile((prev) => ({
              ...prev!,
              image: response.imageUrl,
            }));
          }
          toast.success('Image uploaded successfully!', { id: toastId });
        } catch (err) {
          console.error('Upload error', err);
          toast.error( 'Image upload failed.', { id: toastId });
        } finally {
          setUploading(false);
        }
      };

      reader.readAsDataURL(file);
    };


      

  return (
    <div className=" text-white rounded-[32px] p-4 min-h-[100%]  bg-gradient-to-tr from-[#101010] via-[#111914] to-[#114a2c]">
      <div>
        <div className="relative ">
          {formData.image && (
            <img
              src={formData.image}
              alt="Preview"
              className="mt-3 w-24 h-24 rounded-full object-cover  mx-auto border-4"
            />
          )}
          {!formData.image && (
            <img
              src={`https://ui-avatars.com/api/?name=${
                profile ? `${formData.firstName} ${formData.lastName}` : activeAddress
              }&background=random&font-size=0.35&rounded=true`}
              alt="Preview"
              className="mt-3 w-24 h-24 rounded-full object-cover  mx-auto border-4"
            />
          )}
          <div className="z-10 absolute top-[90%] left-[60%]  ">
            <label
              htmlFor="file-upload"
              className="absolute bottom-0 right-0 bg-black p-1.5 rounded-full cursor-pointer border-2"
            >
              <CameraIcon />
            </label>

            {/* Hidden input */}
            <input
              id="file-upload"
              type="file"
              accept="image/*"
              onChange={handleImageUpload}
              className="hidden"
            />
          </div>
        </div>

        <div className="mx-auto mt-3 text-center rounded-[50px] ring-2 p-2 text-sm w-[120px] ring-white">
          Edit profile
        </div>
      </div>

      <form onSubmit={handleSubmit} className="space-y-4  mt-4">
        <div className="grid grid-cols-2 gap-4">
          <div>
            <label htmlFor="firstName" className="block text-sm text-gray-300 mb-1">
              Full name:
            </label>
            <input
              type="text"
              id="firstName"
              name="firstName"
              placeholder="First Name"
              className="w-full px-4 py-3 rounded-lg bg-[#24252D] text-sm text-white outline-none border-[0.5px]  border-[#49454F] focus:ring-1 focus:ring-[#C5EE4F]"
              value={formData.firstName}
              onChange={handleChange}
            />
          </div>
          <div>
            <label htmlFor="lastName" className="block text-sm text-gray-300 mb-1">
              Last name:
            </label>
            <input
              type="text"
              id="lastName"
              name="lastName"
              placeholder="Last Name"
              className="w-full px-4 py-3 rounded-lg bg-[#24252D] text-sm text-white outline-none focus:ring-1 focus:ring-[#C5EE4F]  border-[0.5px]  border-[#49454F]"
              value={formData.lastName}
              onChange={handleChange}
            />
          </div>
        </div>

        <div className="grid grid-cols-2 relative z-50 gap-2">
          <CountrySelect
            value={formData.country}
            onChange={(country) => {
              setFormData((prev) => ({ ...prev, country }));
              fetchStates(country);
            }}
          />

          <StateSelect
            value={formData.stateOfResidence}
            onChange={(state) => setFormData((prev) => ({ ...prev, stateOfResidence: state }))}
            states={states}
            loading={loadingStates}
          />
        </div>

        <div>
          <label htmlFor="email" className="block text-sm text-gray-300 mb-1">
            Email Address:
          </label>
          <input
            type="email"
            id="email"
            name="email"
            placeholder="Email address"
            className="w-full px-4 py-3 rounded-lg text-sm bg-[#24252D]  text-white outline-none focus:ring-1 focus:ring-[#C5EE4F]  border-[0.5px]  border-[#49454F]"
            value={formData.email}
            onChange={handleChange}
          />
        </div>

        <div>
          <label htmlFor="github" className="block text-sm text-gray-300 mb-1">
            Github Link:
          </label>
          <input
            type="text"
            id="github"
            name="githubLink"
            placeholder="Github link"
            className="w-full px-4 py-3 rounded-lg text-sm bg-[#24252D] text-white outline-none focus:ring-1 focus:ring-[#C5EE4F]  border-[0.5px]  border-[#49454F]"
            value={formData.githubLink}
            onChange={handleChange}
          />
        </div>

        <div>
          <label htmlFor="wallet" className="block text-sm text-gray-300 mb-1">
            Wallet Address:
          </label>
          <input
            type="text"
            id="wallet"
            name="wallet"
            placeholder="0x3f5f3b5bf6fb8f3ef6d9f6f65f6f"
            className="w-full px-4 py-3 text-sm rounded-lg bg-[#24252D] text-white outline-none focus:ring-1 focus:ring-[#C5EE4F]  border-[0.5px]  border-[#49454F]"
            value={activeAddress}
            disabled
          />
        </div>

        <button
          type="submit"
          disabled={loading}
          className={`border h-[56px] w-full bg-white text-black rounded-lg font-semibold justify-center flex items-center gap-2 ${
            loading ? 'opacity-50 cursor-not-allowed' : 'hover:bg-opacity-90'
          }`}
        >
          {loading ? (
            <>
              <Loader2 className="animate-spin" />
              Updating...
            </>
          ) : (
            'Submit Changes'
          )}
        </button>
      </form>
    </div>
  );
};

export default EditProfile;

